# PubQuest Data Exploration / Cleaning

In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

## Load in data

In [3]:
pq_2009 = pd.read_excel('data/Breweries_Philadelphia_GentrificationStudy.xlsx', sheet_name=0)
pq_2009

,X,Y,NAME,ADDRESS,CITY,STATE,ZIP,TYPE
0,-75.218824,40.022126,Manayunk Brewery & Restaurant,4120 Main St.,Philadelphia,PA,19127,BrewPub
1,-75.165656,39.949881,Nodding Head Brewery & Restaurant,1516 Sansom St.,Philadelphia,PA,19102,BrewPub
2,-75.136100,39.962594,Yards Brewing Co.,901 N. Delaware Ave.,Philadelphia,PA,19123,MicroBrewery
3,-75.143400,39.948200,Triumph Brewing Co.,117 Chestnut St.,Philadelphia,PA,19106,BrewPub
4,-75.222732,39.947659,Dock Street Brewing Co.,701 S. 50th St.,Philadelphia,PA,19143,BrewPub
5,-75.127752,39.982746,Philadelphia Brewing Co.,2423 Amber St.,Philadelphia,PA,19125,MicroBrewery
6,-75.190340,40.059228,Earth Bread + Brewery,7136 Germantown Ave.,Philadelphia,PA,19119,BrewPub
7,-75.171429,39.962411,Tiedhouse (General Lafayette Brewery),2001 Hamilton St.,Philadelphia,PA,19130,BrewHouse

In [4]:
pq_2015 = pd.read_excel('data/Breweries_Philadelphia_GentrificationStudy.xlsx', sheet_name=1)
pq_2015

,X,Y,NAME,ADDRESS,CITY,STATE,ZIP,TYPE
0,-75.143400,39.948200,2nd Story Brewing Co.,117 Chestnut St.,Philadelphia,PA,19106,BrewPub
1,-75.108667,39.992811,Do Good Brewing,3245 Amber St.,Philadelphia,PA,19134,Brewery
2,-75.222732,39.947659,Dock Street Brewing Co.,701 S. 50th St.,Philadelphia,PA,19143,BrewPub
3,-75.190340,40.059228,Earth Bread + Brewery,7136 Germantown Ave.,Philadelphia,PA,19119,BrewPub
4,-75.159625,39.948782,Farmers' Cabinet,1113 Walnut St.,Philadelphia,PA,19107,BrewHouse
5,-75.205079,40.075189,Iron Hill Brewery & Restaurant,8400 Germantown Ave.,Philadelphia,PA,19118,BrewPub
6,-75.218824,40.022126,Manayunk Brewery & Restaurant,4120 Main St.,Philadelphia,PA,19127,BrewPub
7,-75.127752,39.982746,Philadelphia Brewing Co.,2423 Amber St.,Philadelphia,PA,19125,Brewery
8,-75.143479,39.977079,Saint Benjamin Brewing Co.,1705 N. 5th Ave.,Philadelphia,PA,19125,Brewery
9,-75.167747,39.904646,Victory Beer Hall,1100 Pattison Ave.,Philadelphia,PA,19148,BrewHouse
10,-75.136100,39.962594,Yards Brewing Co.,901 N. Delaware Ave.,Philadelphia,PA,19123,Brewery

In [5]:
pq_2019 = pd.read_excel('data/Breweries_Philadelphia_GentrificationStudy.xlsx', sheet_name=2)
pq_2019

,X,Y,NAME,ADDRESS,CITY,STATE,ZIP,TYPE
0,-75.143400,39.948200,2nd Story Brewing Co.,117 Chestnut St.,Philadelphia,PA,19106,BrewPub
1,-75.178879,39.923969,Brewery ARS,1927 W. Passyunk Ave.,Philadelphia,PA,19145,Brewery
2,-75.166107,39.966969,Brewery Techne @ Bar Hygge,1720 Fairmount Ave.,Philadelphia,PA,19130,BrewPub
3,-75.202798,40.073763,Chestnut Hill Brewing Co.,8221 Germantown Ave.,Philadelphia,PA,19118,BrewPub
4,-75.180840,39.974457,Crime & Punishment Brewing,2711 W. Girard Ave.,Philadelphia,PA,19130,Brewery
5,-75.108667,39.992811,Do Good Brewing,3245 Amber St.,Philadelphia,PA,19134,Brewery
6,-75.222732,39.947659,Dock Street Brewing Co.,701 S. 50th St.,Philadelphia,PA,19143,BrewPub
7,-75.190340,40.059228,Earth Bread + Brewery,7136 Germantown Ave.,Philadelphia,PA,19119,BrewPub
8,-75.136367,39.975722,Evil Genius Beer Co.,1727 N. Front St.,Philadelphia,PA,19122,BrewPub
9,-75.137708,39.975788,Fermentery Form,1700 N. Palethorpe St.,Philadelphia,PA,19122,Brewery
10,-75.134010,39.967712,Fishtown Brewpub,1101 Frankford Ave.,Philadelphia,PA,19125,BrewPub
11,-75.135130,39.964850,Goose Island Brewhouse,1002 Canal St.,Philadelphia,PA,19123,BrewPubX
12,-75.205079,40.075189,Iron Hill Brewery & Restaurant,8400 Germantown Ave.,Philadelphia,PA,19118,BrewPub
13,-75.159092,39.951797,Iron Hill Brewery & Restaurant,1150 Market St.,Philadelphia,PA,19107,BrewPub
14,-75.155504,39.960491,Love City Brewing,1016 Buttonwood St.,Philadelphia,PA,19123,Brewery
15,-75.218824,40.022126,Manayunk Brewery & Restaurant,4120 Main St.,Philadelphia,PA,19127,BrewPub
16,-75.127752,39.982746,Philadelphia Brewing Co.,2423 Amber St.,Philadelphia,PA,19125,Brewery
17,-75.189990,39.938300,Point Breeze Brewing,1225 S. 28th St.,Philadelphia,PA,19146,Brewery
18,-75.154221,39.961147,Roy-Pitz Barrel House,990 Spring Garden St.,Philadelphia,PA,19123,BrewPub
19,-75.110661,39.992619,Sacred Vice Brewing,3237 Amber St.,Philadelphia,PA,19134,Brewery
20,-75.173031,39.926384,Second District Brewing Co.,1939 S. Bancroft St.,Philadelphia,PA,19145,BrewPub
21,-75.140075,39.966742,Urban Village Brewing Co.,1001 N. 2nd St.,Philadelphia,PA,19123,BrewPub
22,-75.167747,39.904646,Victory Beer Hall,1100 Pattison Ave.,Philadelphia,PA,19148,BrewHouse
23,-75.200470,40.013710,Wissahickon Brewing Co.,3705 W. School House Lane,Philadelphia,PA,19129,Brewery
24,-75.147040,39.960580,Yards Brewing Co.,500 Spring Garden St.,Philadelphia,PA,19123,Brewery

In [6]:
pq_2023 = pd.read_excel('data/Breweries_Philadelphia_GentrificationStudy.xlsx', sheet_name=3)
pq_2023

,X,Y,NAME,ADDRESS,CITY,STATE,ZIP,TYPE
0,-75.143400,39.948200,2nd Story Brewing Co.,117 Chestnut St.,Philadelphia,PA,19106,BrewPub
1,-75.161050,40.023150,Attic Brewing Co.,137 W. Berkley St.,Philadelphia,PA,19144,Brewery
2,-75.222730,40.025340,Bald Birds Brewing,4323 Main St.,Philadelphia,PA,19127,BrewHouse
3,-75.178879,39.923969,Brewery ARS,1927 W. Passyunk Ave.,Philadelphia,PA,19145,Brewery
4,-75.128811,39.979929,Brewery ARS,2223 Frankford Ave.,Philadelphia,PA,19125,Brewery
5,-75.166107,39.966969,Brewery Techne @ Bar Hygge,1720 Fairmount Ave.,Philadelphia,PA,19130,BrewPub
6,-75.222732,39.947659,Carbon Copy,701 S. 50th St.,Philadelphia,PA,19143,BrewPub
7,-75.160098,39.932867,Cartesian Brewing Co.,1326 E Passyunk Ave.,Philadelphia,PA,19147,Brewery
8,-75.202798,40.073763,Chestnut Hill Brewing Co.,8221 Germantown Ave.,Philadelphia,PA,19118,BrewPub
9,-75.135520,39.962760,Craft Hall,901 N. Delaware Ave.,Philadelphia,PA,19123,BrewPub
10,-75.180840,39.974457,Crime & Punishment Brewing,2711 W. Girard Ave.,Philadelphia,PA,19130,Brewery
11,-75.108667,39.992811,Do Good Brewing,3245 Amber St.,Philadelphia,PA,19134,Brewery
12,-75.181488,39.939183,Dock Street Brewing Co.,2118 Washington Ave.,Philadelphia,PA,19146,BrewPub
13,-75.136367,39.975722,Evil Genius Beer Co.,1727 N. Front St.,Philadelphia,PA,19122,BrewPub
14,-75.134010,39.967712,Fishtown Brewpub,1101 Frankford Ave.,Philadelphia,PA,19125,BrewPub
15,-75.143614,39.977318,Human Robot Brewing Co.,1710 N. 5th St.,Philadelphia,PA,19122,Brewery
16,-75.179970,39.951623,Human Robot Brewing Co.,2401 Walnut St.,Philadelphia,PA,19103,BrewHouse
17,-75.205079,40.075189,Iron Hill Brewery & Restaurant,8400 Germantown Ave.,Philadelphia,PA,19118,BrewPub
18,-75.159092,39.951797,Iron Hill Brewery & Restaurant,1150 Market St.,Philadelphia,PA,19107,BrewPub
19,-75.155504,39.960491,Love City Brewing,1016 Buttonwood St.,Philadelphia,PA,19123,Brewery
20,-75.135520,39.962760,Mainstay Independent Brewing,901 N. Delaware Ave.,Philadelphia,PA,19123,Brewery
21,-75.217100,40.034916,New Ridge Brewing Co.,6168 Ridge Ave.,Philadelphia,PA,19128,BrewPub
22,-75.135073,39.964719,Other Half Brewing Co.,1002 Canal St.,Philadelphia,PA,19123,BrewPub
23,-75.127129,39.982378,Philadelphia Brewing Co.,2440 Frankford Ave.,Philadelphia,PA,19125,Brewery
24,-75.189990,39.938300,Point Breeze Brewing,1225 S. 28th St.,Philadelphia,PA,19146,Brewery
25,-75.139610,39.973640,Punch Buggy Brewing,1445 N. American St.,Philadelphia,PA,19122,Brewery
26,-75.110661,39.992619,Sacred Vice Brewing,3237 Amber St.,Philadelphia,PA,19134,Brewery
27,-75.173031,39.926384,Second District Brewing Co.,1939 S. Bancroft St.,Philadelphia,PA,19145,BrewPub
28,-75.129250,39.980160,St. Oner's by Tired Hands Brewing Co.,2218 Frankford Ave.,Philadelphia,PA,19125,BrewHouse
29,-75.153530,39.962110,Triple Bottom Brewing Co.,915 Spring Garden St.,Philadelphia,PA,19123,Brewery
30,-75.140075,39.966742,Urban Village Brewing Co.,1001 N. 2nd St.,Philadelphia,PA,19123,BrewPub
31,-75.167747,39.904646,Victory Beer Hall,1100 Pattison Ave.,Philadelphia,PA,19148,BrewHouse
32,-75.200470,40.013710,Wissahickon Brewing Co.,3705 W. School House Lane,Philadelphia,PA,19129,Brewery
33,-75.147040,39.960580,Yards Brewing Co.,500 Spring Garden St.,Philadelphia,PA,19123,Brewery

### Concatenate data together and add indicators for what year it's from

Unique ID now becomes NAME x data_year

In [8]:
pq_2009['date_year'] = 2009
pq_2015['date_year'] = 2015
pq_2019['date_year'] = 2019
pq_2023['date_year'] = 2023

pq = pd.concat([pq_2009,pq_2015, pq_2019, pq_2023])
pq

,X,Y,NAME,ADDRESS,CITY,STATE,ZIP,TYPE,date_year
0,-75.218824,40.022126,Manayunk Brewery & Restaurant,4120 Main St.,Philadelphia,PA,19127,BrewPub,2009
1,-75.165656,39.949881,Nodding Head Brewery & Restaurant,1516 Sansom St.,Philadelphia,PA,19102,BrewPub,2009
2,-75.136100,39.962594,Yards Brewing Co.,901 N. Delaware Ave.,Philadelphia,PA,19123,MicroBrewery,2009
3,-75.143400,39.948200,Triumph Brewing Co.,117 Chestnut St.,Philadelphia,PA,19106,BrewPub,2009
4,-75.222732,39.947659,Dock Street Brewing Co.,701 S. 50th St.,Philadelphia,PA,19143,BrewPub,2009
...,...,...,...,...,...,...,...,...,...
29,-75.153530,39.962110,Triple Bottom Brewing Co.,915 Spring Garden St.,Philadelphia,PA,19123,Brewery,2023
30,-75.140075,39.966742,Urban Village Brewing Co.,1001 N. 2nd St.,Philadelphia,PA,19123,BrewPub,2023
31,-75.167747,39.904646,Victory Beer Hall,1100 Pattison Ave.,Philadelphia,PA,19148,BrewHouse,2023
32,-75.200470,40.013710,Wissahickon Brewing Co.,3705 W. School House Lane,Philadelphia,PA,19129,Brewery,2023
33,-75.147040,39.960580,Yards Brewing Co.,500 Spring Garden St.,Philadelphia,PA,19123,Brewery,2023

## Geotag

In [9]:
pq_gdf = gpd.GeoDataFrame(pq, 
                          geometry=gpd.points_from_xy(pq.Y, pq.X))
pq_gdf

,X,Y,NAME,ADDRESS,CITY,STATE,ZIP,TYPE,date_year,geometry
0,-75.218824,40.022126,Manayunk Brewery & Restaurant,4120 Main St.,Philadelphia,PA,19127,BrewPub,2009,POINT (40.02213 -75.21882)
1,-75.165656,39.949881,Nodding Head Brewery & Restaurant,1516 Sansom St.,Philadelphia,PA,19102,BrewPub,2009,POINT (39.94988 -75.16566)
2,-75.136100,39.962594,Yards Brewing Co.,901 N. Delaware Ave.,Philadelphia,PA,19123,MicroBrewery,2009,POINT (39.96259 -75.1361)
3,-75.143400,39.948200,Triumph Brewing Co.,117 Chestnut St.,Philadelphia,PA,19106,BrewPub,2009,POINT (39.9482 -75.1434)
4,-75.222732,39.947659,Dock Street Brewing Co.,701 S. 50th St.,Philadelphia,PA,19143,BrewPub,2009,POINT (39.94766 -75.22273)
...,...,...,...,...,...,...,...,...,...,...
29,-75.153530,39.962110,Triple Bottom Brewing Co.,915 Spring Garden St.,Philadelphia,PA,19123,Brewery,2023,POINT (39.96211 -75.15353)
30,-75.140075,39.966742,Urban Village Brewing Co.,1001 N. 2nd St.,Philadelphia,PA,19123,BrewPub,2023,POINT (39.96674 -75.14008)
31,-75.167747,39.904646,Victory Beer Hall,1100 Pattison Ave.,Philadelphia,PA,19148,BrewHouse,2023,POINT (39.90465 -75.16775)
32,-75.200470,40.013710,Wissahickon Brewing Co.,3705 W. School House Lane,Philadelphia,PA,19129,Brewery,2023,POINT (40.01371 -75.20047)
33,-75.147040,39.960580,Yards Brewing Co.,500 Spring Garden St.,Philadelphia,PA,19123,Brewery,2023,POINT (39.96058 -75.14704)

In [11]:
pq_gdf = pq_gdf.set_crs(crs="EPSG:4326")
pq_gdf = pq_gdf.to_crs(crs="EPSG:2272")

In [12]:
pq_gdf.crs

<Projected CRS: EPSG:2272>
Name: NAD83 / Pennsylvania South (ftUS)
Axis Info [cartesian]:
- X[east]: Easting (US survey foot)
- Y[north]: Northing (US survey foot)
Area of Use:
- name: United States (USA) - Pennsylvania - counties of Adams; Allegheny; Armstrong; Beaver; Bedford; Berks; Blair; Bucks; Butler; Cambria; Chester; Cumberland; Dauphin; Delaware; Fayette; Franklin; Fulton; Greene; Huntingdon; Indiana; Juniata; Lancaster; Lawrence; Lebanon; Lehigh; Mifflin; Montgomery; Northampton; Perry; Philadelphia; Schuylkill; Snyder; Somerset; Washington; Westmoreland; York.
- bounds: (-80.53, 39.71, -74.72, 41.18)
Coordinate Operation:
- name: SPCS83 Pennsylvania South zone (US survey foot)
- method: Lambert Conic Conformal (2SP)
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [13]:
pq_gdf.to_file('data/all_pq_data.gpkg')